# Generated by Django 5.1.1 on 2024-09-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0002_remove_song_artist_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(choices=[('', 'Raggea'), ('2', 'FreeStyle'), ('3', 'Rap')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
