# Generated by Django 5.1.1 on 2024-09-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0003_alter_song_title_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='type',
            field=models.CharField(choices=[('', 'Raggea'), ('2', 'FreeStyle'), ('3', 'Rap')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
