# Generated by Django 5.1.1 on 2024-09-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0004_song_type_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(help_text='Enter music Album', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(help_text='Enter music title', max_length=50),
        ),
    ]
