# Generated by Django 5.1.1 on 2024-09-29 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0005_alter_album_title_alter_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.CreateModel(
            name='song_instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('a', 'Available'), ('p', 'Paid For'), ('f', 'free')], default='a', help_text='song availability', max_length=1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysport.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysport.song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='mysport.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysport.artist'),
        ),
    ]
