# Generated by Django 5.1.1 on 2024-09-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0006_artist_date_of_birth_song_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=100),
        ),
    ]
