# Generated by Django 5.1.1 on 2024-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0007_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='type',
            field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('hip_hop', 'Hip Hop'), ('electronic', 'Electronic')], default=None, max_length=100),
        ),
    ]
